services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: e2e_zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: e2e_kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
      - "29092:29092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,PLAINTEXT_HOST://kafka:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT_HOST
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"

  timeplus:
    image: timeplus/proton:3.0.3
    container_name: e2e_timeplus
    ports:
     - "3218:3218" # HTTP Streaming
     - "8123:8123" # HTTP Snapshot
     - "8463:8463" # TCP Streaming
     - "5432:5432" # Postgres Snapshot
     - "7587:7587" # TCP Snapshot

  clickhouse:
    image: clickhouse/clickhouse-server:25.8
    container_name: e2e_clickhouse
    ports:
      - "9000:9000"  # Native protocol
      - "8124:8123"  # HTTP protocol (different from Timeplus 8123)
    environment:
      CLICKHOUSE_DB: default
      CLICKHOUSE_USER: default
      CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT: 1
      CLICKHOUSE_PASSWORD: ""
    ulimits:
      nofile:
        soft: 262144
        hard: 262144

networks:
  default:
    name: e2e_network
